<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<Protobuf Include="Protos\file.proto" GrpcServices="Both" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Google.Api.CommonProtos" Version="2.16.0" />
		<PackageReference Include="google.protobuf" Version="3.28.3" />
		<PackageReference Include="Grpc.AspNetCore" Version="2.57.0" />
		<PackageReference Include="Grpc.AspNetCore.Web" Version="2.66.0" />
		<PackageReference Include="linq2db" Version="5.4.1" />
		<PackageReference Include="Linq2db.AspNet" Version="5.4.1" />
		<PackageReference Include="linq2db.PostgreSQL" Version="5.4.1" />
		<PackageReference Include="Linq2Db.Tools" Version="5.4.1" />
		<PackageReference Include="Microsoft.AspNetCore.Grpc.JsonTranscoding" Version="8.0.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		  <PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Npgsql" Version="9.0.2" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.postgreSql" Version="8.0.10" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.postgreSql.Design" Version="1.1.0" />
	</ItemGroup>

</Project>
